version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql 
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    container_name: pma 
    links:
      - database
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    ports:
      - "8080:80"
    restart: always
  solution:
    image: solution
    build: images/solution
    container_name: solution
    links:
      - database 
    environment:
      - DB_HOST=database
      - DB_UN=codetest
      - DB_PW=swordfish
    command: ["./entrypoint.sh"]
    volumes:
      - ./data:/data